language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx
  - jruby-head
  - ruby-head
  - 1.8.7
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
script: bundle exec rspec -c spec
notifications:
  irc: "irc.freenode.org#travis"
  email:
    recepients:
      - michaelklishin@me.com

